alias zshconfig="code ~/.zshrc"
alias ohmyzsh="code ~/.oh-my-zsh"
alias baem="pwsh -c Finish-Release"
alias dry-baem="pwsh -c 'Finish-Release -DryRun \$True'"
alias refresh="git com && git pfo && git rmu"
